name: Selenium Pytest Tutorial Ninja Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest and Generate Report
        run: |
          pytest tests/ --html=report.html --self-contained-html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html
